### ISSUE TITLE
Q about form field generator

### ISSUE THREAD

**Issue by ErieMeyer** [Threespot/letgirlslearn#10]
Hi! Am I making up that you guys made an accessible form generator for this? Would love to see it if so!

cc @meiqimichellen @jjoteal

**Comment by cmc333333** [comment]
Talked to @meiqimichelle out of band. Short version:
Let Girls Learn doesn't have a form, but the donations platform (e.g. https://beta.peacecorps.gov/donate/fund/agriculture-fund/payment/?payment_amount=50) does. Nothing super novel, there.

@annalee [added](https://github.com/18F/peacecorps-site/pull/192) some tweaks to the django admin to account for color blindness, but I'm not sure that's what you're looking for.
