### ISSUE TITLE
Site Build & Parallax Issues 

### ISSUE THREAD

**Issue by sshami** [Threespot/letgirlslearn#9]
Hi,

I’m having issues building the site. It seems like the issue is with the grunt-exorcise (1.0.0) package no longer working correctly. I get some source map errors. Details in the link below:
https://github.com/mikefrey/grunt-exorcise/issues/10

I updated the grunt-exorcise line in package.json to use the latest 2.0.0 version, reinstalled using npm, and then grunt build ran successfully. However, when I tested on my local, it seems like the build broke the parallax scrolling. Any apparent reason this might be happening?

Thanks,
Saad

**Comment by cmc333333** [comment]
Hey @sshami , I'll be able to take a look a bit later this week. In the mean time open up chrome's developer tools and see if there are any javascript warnings -- they may give you the clue forward. Anything jump out at you @msecret ?

**Comment by cmc333333** [comment]
@sshami - just a quick update - I can definitely recreate but haven't had any luck with a solution yet. I'm betting that it's an issue with the skrollr version.

**Comment by cmc333333** [comment]
@sshami pull down the latest master and this should be fixed. I'll push the latest code to the demo site later today. Please close this issue if it's all working for you

**Comment by sshami** [comment]
@cmc333333 Thanks! It's working for me now
